env:
  global:
    - CC_TEST_REPORTER_ID=3ca09808c18a3fb0a12a7b113aeca064acf88831f8a36ee2e9fda89ca37b0650
language: ruby
rvm:
  - 2.4.10
  - 2.5.7
  - 2.6.6
  - 2.7.1
  - truffleruby
  - ruby-head
install: bundle install
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - bundle exec rake test
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
jobs:
  allow_failures:
    - rvm: ruby-head
    - rvm: truffleruby
